[package]
name = "peniko"
version = "0.1.0"
authors = ["Chad Brokaw <cbrokaw@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Primitive types for styling vector graphics"
keywords = ["graphics", "vector", "style"]
categories = ["graphics"]
repository = "https://github.com/linebender/peniko"
homepage = "https://github.com/linebender/peniko"
readme = "README.md"

[dependencies]
kurbo = "0.9.5"
smallvec = "1.8.0"
